on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        - run: node index.js

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Display Node.js version
        run: node --version

      - name: Display npm version
        run: npm --version
